### ISSUE TITLE
unhashable type: 'AnyUrlValue'

### ISSUE THREAD

**Issue by bashu** [bashu/fluentcms-forms-builder#3]
```python
Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/middleware.py", line 57, in _inner_render
    return orig_render(response)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/tag_parser/basetags.py", line 176, in render
    return self.render_tag(context, *tag_args, **tag_kwargs)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/tag_parser/basetags.py", line 372, in render_tag
    return self.get_value(context, *tag_args, **tag_kwargs)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/templatetags/fluent_contents_tags.py", line 222, in get_value
    fallback_language=fallback_language
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/rendering/main.py", line 58, in render_placeholder
    fallback_language=fallback_language
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/rendering/core.py", line 425, in render_placeholder
    output = self.render_items(placeholder, items, parent_object, template_name, cachable)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/rendering/core.py", line 208, in render_items
    self._render_uncached_items(result.remaining_items, result=result)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/rendering/core.py", line 274, in _render_uncached_items
    output = self.render_item(contentitem)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/rendering/core.py", line 299, in render_item
    return contentitem.plugin._render_contentitem(self.request, contentitem)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/fluent_contents/extensions/pluginbase.py", line 319, in _render_contentitem
    result = self.render(request=request, instance=instance)
  File "/Users/bashu/Projects/fluentcms-forms-builder/fluentcms_forms_builder/content_plugins.py", line 54, in render
    return redirect(form.redirect_url)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/shortcuts.py", line 56, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/shortcuts.py", line 147, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/urls/resolvers.py", line 438, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/utils/datastructures.py", line 157, in getlist
    return self._getlist(key, default, force_list=True)
  File "/Users/bashu/.virtualenvs/fluentcms-forms-builder/lib/python3.6/site-packages/django/utils/datastructures.py", line 142, in _getlist
    values = super(MultiValueDict, self).__getitem__(key)
TypeError: unhashable type: 'AnyUrlValue'
```

**Comment by bashu** [comment]
@cybersimon stay tuned...
